# -*- coding: utf-8 -*-
"""
键型分析配置兼容层。

说明：
1. 真实配置项已迁移到插件根目录 config.py 的 Config 中。
2. 本文件仅做“旧常量名 -> nonebot 配置对象”的桥接，避免影响现有算法模块导入。
3. 若需调参，请改根配置中的同名字段。
"""

from __future__ import annotations

from nonebot import get_plugin_config

from ...config import Config

config = get_plugin_config(Config)

CORE_RATING_MULTIPLIER: dict[str, float] = config.CORE_RATING_MULTIPLIER
SUBTYPE_RATING_MULTIPLIER_BY_MODE: dict[str, dict[str, float]] = config.SUBTYPE_RATING_MULTIPLIER_BY_MODE
RC_CORE_LN_SCALE: float = config.RC_CORE_LN_SCALE
RC_LN_CORE_SCALE: float = config.RC_LN_CORE_SCALE
RELEASE_WITH_DW_MULTIPLIER: float = config.RELEASE_WITH_DW_MULTIPLIER
LN_MODE_LOW_THRESHOLD: float = config.LN_MODE_LOW_THRESHOLD
LN_MODE_HIGH_THRESHOLD: float = config.LN_MODE_HIGH_THRESHOLD
HB_ROW_RATIO_THRESHOLD: float = config.HB_ROW_RATIO_THRESHOLD

BPM_CLUSTER_THRESHOLD: float = config.BPM_CLUSTER_THRESHOLD
PATTERN_STABILITY_THRESHOLD: float = config.PATTERN_STABILITY_THRESHOLD
IMPORTANT_CLUSTER_RATIO: float = config.IMPORTANT_CLUSTER_RATIO
CATEGORY_JS_HS_SECONDARY_RATIO: float = config.CATEGORY_JS_HS_SECONDARY_RATIO
SV_AMOUNT_THRESHOLD: float = config.SV_AMOUNT_THRESHOLD
CLUSTER_SPECIFIC_NAME_MIN_RATIO: float = config.CLUSTER_SPECIFIC_NAME_MIN_RATIO
ENABLE_MULTI_LABEL_SAME_WINDOW: bool = config.ENABLE_MULTI_LABEL_SAME_WINDOW

COORDINATION_SPECIFIC_ORDER: list[str] = config.COORDINATION_SPECIFIC_ORDER
DENSITY_SPECIFIC_ORDER: list[str] = config.DENSITY_SPECIFIC_ORDER
WILDCARD_SPECIFIC_ORDER: list[str] = config.WILDCARD_SPECIFIC_ORDER

JACKY_MIN_BPM: float = config.JACKY_MIN_BPM
SHIELD_MAX_BEAT_RATIO: float = config.SHIELD_MAX_BEAT_RATIO
INVERSE_GAP_TOLERANCE_MS: float = config.INVERSE_GAP_TOLERANCE_MS
INVERSE_MIN_FILLED_LANES: int = config.INVERSE_MIN_FILLED_LANES
RELEASE_SCAN_ROWS: int = config.RELEASE_SCAN_ROWS
RELEASE_MIN_TAIL_ROWS: int = config.RELEASE_MIN_TAIL_ROWS
RELEASE_ROLL_POINTS: int = config.RELEASE_ROLL_POINTS
RELEASE_FULL_MATCH_ROWS: int = config.RELEASE_FULL_MATCH_ROWS
JACKY_CONTEXT_WINDOW: int = config.JACKY_CONTEXT_WINDOW
JACKY_FALLBACK_MAX_MSPB: float = config.JACKY_FALLBACK_MAX_MSPB
